### ISSUE TITLE
Apps are created in state TASK_UNKNOWN

### ISSUE THREAD

**Issue by brian-avery** [verizonlabs/hydrogen#36]
After calling a post on /hydrogen/v1/api/app, I get a response stating that the state is TASK_UNKNOWN. Doing a list though, I see apps go through staging state and then running state.

**Comment by thanset** [comment]
@aaronjwood I think we can extend this to a TASK_QUEUED or something similar?

**Comment by aaronjwood** [comment]
In #40 I just omitted the state from the response since I thought that the message itself would be good enough. https://github.com/verizonlabs/hydrogen/pull/40#issuecomment-330354975

**Comment by thanset** [comment]
State field would be good to debug where a task is (potentially) stuck?

**Comment by aaronjwood** [comment]
Do you mean for other endpoints? I can't see how we'd get stuck on a deployment since we have things so that it either fails or succeeds. It seems kind of atomic for when a user deploys and we set this state.

I think the state is useful in a few of the other endpoints for sure. If you want to keep the state maybe we can get rid of the message that's sent back on deployment and instead just send back something like
```
{
"state": "TASK_QUEUED"
}
```
and maybe add back in the `name` field since the message contains that now...?
