### ISSUE TITLE
Endpoints with a trailing slash yield 404

### ISSUE THREAD

**Issue by brian-avery** [verizonlabs/hydrogen#41]
Currently, hitting 198.159.136.23/hydrogen/v1/api/app works but hitting 198.159.136.23/hydrogen/v1/api/app/ gives a 404. I believe Go Gin gives the option to include the slash at the end at the same endpoint. Should we support it?

**Comment by aaronjwood** [comment]
@thanset what do you think about this? I've seen a bunch arguments/discussions about how to treat this situation. It could be viewed that resources ending with a `/` indicate a new resource group and should be treated as a totally separate endpoint than the same thing without a trailing `/`. OTOH I've seen people either treat them as the same thing or redirect.

**Comment by thanset** [comment]
We don't use the `gin` library @brian-avery, but I prefer to stick with the RFC (3986) standard of using a trailing slash to indicate another directory.  Since we have additional resources on-top of of the application `/app/all endpoint`, we should redirect all requests to `/app` to `/app/` to indicate there are further resources.
